[tool.poetry]
name = "zeta-py"
version = "0.1.0"
description = "Python SDK for Zeta Markets"
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.9"
anchorpy = "^0.18.0"
solana = "^0.30.2"
ruff = "^0.0.284"
solders = "^0.18.1"
pyserum = "^0.5.0-alpha.0"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
main = "zeta_py.main:main"

[tool.ruff]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
