[tool.poetry]
name = "zeta-py"
version = "0.1.0"
description = "Python SDK for Zeta Markets"
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.11"
solana = "^0.30.2"
solders = "^0.18.1"
requests = "^2.31.0"
anchorpy = { path = "../anchorpy" }
psycopg = {extras = ["binary", "pool"], version = "^3.1.10"}

[tool.poetry.group.dev.dependencies]
ruff = "^0.0.284"
perspective-python = "^2.5.0"
ipykernel = "^6.25.1"
isort = "^5.12.0"
black = {extras = ["jupyter"], version = "^23.7.0"}
python-dotenv = "^1.0.0"
ccxt = "^4.0.78"

[tool.poe]
poetry_command = ""

[tool.poe.tasks]
black = "black zeta_py"
isort = "isort zeta_py"
format = ["black", "isort"]
lint = "ruff check zeta_py"

[tool.ruff]
line-length=120
exclude = ["zeta_py/zeta_client", ".venv"]

[tool.black]
line-length=120

[tool.isort]
profile = "black"
skip = ["zeta_py/zeta_client"]

[tool.poetry.scripts]
main = "zeta_py.main:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
